import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { ArrowLeftRight, ListChecks, PlusCircle, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { format } from "date-fns";
import { th } from "date-fns/locale";
import BillboardSelect from "@/components/billboard/BillboardSelect";
import { SymptomSelect } from "@/components/media-player/SymptomSelect";
import { SwapWizardDialog } from "@/components/swap/SwapWizardDialog";

interface SwapRequest {
  id: string;
  document_no: string;
  billboard_id: string | null;
  symptom_id: string | null;
  symptom_other: string | null;
  description: string | null;
  technician_name: string | null;
  technician_phone: string | null;
  priority: string;
  status: string;
  created_at: string;
  notes: string | null;
}

const STATUS_LABELS: Record<string, { label: string; variant: "default" | "secondary" | "destructive" | "outline" }> = {
  pending: { label: "รอดำเนินการ", variant: "secondary" },
  in_progress: { label: "กำลัง Swap", variant: "default" },
  completed: { label: "Swap แล้ว", variant: "default" },
  rejected: { label: "Reject", variant: "destructive" },
  cancelled: { label: "ยกเลิก", variant: "outline" },
};

const PRIORITY_LABELS: Record<string, string> = {
  low: "ต่ำ",
  normal: "ปกติ",
  high: "สูง",
  urgent: "ด่วนมาก",
};

export default function SwapWizard() {
  const { user } = useAuth();
  const [requests, setRequests] = useState<SwapRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState("list");
  const [wizardOpen, setWizardOpen] = useState(false);
  const [selectedRequest, setSelectedRequest] = useState<SwapRequest | null>(null);

  // Form state for new request
  const [billboardId, setBillboardId] = useState("");
  const [symptomId, setSymptomId] = useState("");
  const [symptomOther, setSymptomOther] = useState("");
  const [description, setDescription] = useState("");
  const [technicianName, setTechnicianName] = useState("");
  const [technicianPhone, setTechnicianPhone] = useState("");
  const [priority, setPriority] = useState("normal");
  const [submitting, setSubmitting] = useState(false);

  const fetchRequests = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("swap_requests")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(200);
    if (error) {
      toast.error("โหลดข้อมูลไม่สำเร็จ");
    } else {
      setRequests((data as SwapRequest[]) || []);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchRequests();
  }, []);

  const stats = useMemo(() => {
    const total = requests.length;
    const pending = requests.filter((r) => r.status === "pending").length;
    const inProgress = requests.filter((r) => r.status === "in_progress").length;
    const completed = requests.filter((r) => r.status === "completed").length;
    return { total, pending, inProgress, completed };
  }, [requests]);

  const resetForm = () => {
    setBillboardId("");
    setSymptomId("");
    setSymptomOther("");
    setDescription("");
    setTechnicianName("");
    setTechnicianPhone("");
    setPriority("normal");
  };

  const handleSubmit = async () => {
    if (!billboardId) {
      toast.error("กรุณาเลือกป้ายโฆษณา");
      return;
    }
    if (!symptomId && !symptomOther.trim()) {
      toast.error("กรุณาระบุอาการเสีย");
      return;
    }
    setSubmitting(true);
    const { error } = await supabase.from("swap_requests").insert({
      billboard_id: billboardId,
      symptom_id: symptomId || null,
      symptom_other: symptomOther.trim() || null,
      description: description.trim() || null,
      technician_name: technicianName.trim() || null,
      technician_phone: technicianPhone.trim() || null,
      priority,
      status: "pending",
      created_by: user?.id ?? null,
      document_no: "", // auto-generated by trigger
    });
    setSubmitting(false);
    if (error) {
      toast.error("บันทึกไม่สำเร็จ: " + error.message);
      return;
    }
    toast.success("สร้างคำขอ Swap แล้ว");
    resetForm();
    setActiveTab("list");
    fetchRequests();
  };

  const openWizard = (req: SwapRequest) => {
    setSelectedRequest(req);
    setWizardOpen(true);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
            <ArrowLeftRight className="h-8 w-8 text-primary" />
            Swap Wizard
          </h1>
          <p className="text-muted-foreground mt-1">
            ระบบสลับเครื่อง Media Player / อุปกรณ์ ระหว่าง Spare กับเครื่องที่ติดตั้งหน้างาน
          </p>
        </div>
        <Button variant="outline" onClick={fetchRequests} disabled={loading}>
          <RefreshCw className={`h-4 w-4 mr-2 ${loading ? "animate-spin" : ""}`} />
          โหลดใหม่
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>คำขอทั้งหมด</CardDescription>
            <CardTitle className="text-3xl">{stats.total}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>รอดำเนินการ</CardDescription>
            <CardTitle className="text-3xl text-warning">{stats.pending}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>กำลัง Swap</CardDescription>
            <CardTitle className="text-3xl text-primary">{stats.inProgress}</CardTitle>
          </CardHeader>
        </Card>
        <Card>
          <CardHeader className="pb-2">
            <CardDescription>Swap แล้ว</CardDescription>
            <CardTitle className="text-3xl text-success">{stats.completed}</CardTitle>
          </CardHeader>
        </Card>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList>
          <TabsTrigger value="list">
            <ListChecks className="h-4 w-4 mr-2" /> รายการคำขอ
          </TabsTrigger>
          <TabsTrigger value="new">
            <PlusCircle className="h-4 w-4 mr-2" /> แจ้ง Swap ใหม่
          </TabsTrigger>
        </TabsList>

        <TabsContent value="list" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle>รายการคำขอ Swap ล่าสุด</CardTitle>
              <CardDescription>คลิก "ดำเนินการ" เพื่อเริ่ม Wizard 3 ขั้น</CardDescription>
            </CardHeader>
            <CardContent>
              {loading ? (
                <div className="text-center py-8 text-muted-foreground">กำลังโหลด...</div>
              ) : requests.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">
                  ยังไม่มีคำขอ — กดแท็บ "แจ้ง Swap ใหม่" เพื่อเริ่ม
                </div>
              ) : (
                <div className="space-y-2">
                  {requests.map((req) => {
                    const status = STATUS_LABELS[req.status] || { label: req.status, variant: "outline" as const };
                    return (
                      <div
                        key={req.id}
                        className="flex items-center justify-between gap-4 p-4 rounded-lg border hover:bg-accent/50 transition-colors flex-wrap"
                      >
                        <div className="flex-1 min-w-[200px] space-y-1">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-mono font-semibold">{req.document_no}</span>
                            <Badge variant={status.variant}>{status.label}</Badge>
                            {req.priority !== "normal" && (
                              <Badge variant="outline">Priority: {PRIORITY_LABELS[req.priority]}</Badge>
                            )}
                          </div>
                          <div className="text-sm text-muted-foreground">
                            {req.description || req.symptom_other || "—"}
                          </div>
                          <div className="text-xs text-muted-foreground">
                            ช่าง: {req.technician_name || "—"} • {format(new Date(req.created_at), "dd MMM yyyy HH:mm", { locale: th })}
                          </div>
                        </div>
                        <div className="flex gap-2">
                          {(req.status === "pending" || req.status === "in_progress") && (
                            <Button size="sm" onClick={() => openWizard(req)}>
                              <ArrowLeftRight className="h-4 w-4 mr-1" /> ดำเนินการ Swap
                            </Button>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="new" className="mt-4">
          <Card>
            <CardHeader>
              <CardTitle>แจ้งคำขอ Swap ใหม่</CardTitle>
              <CardDescription>ขั้นที่ 1: ระบุปัญหา จากนั้นวิศวกรจะกด "ดำเนินการ Swap" เพื่อเข้า Wizard</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>ป้ายโฆษณา *</Label>
                  <BillboardSelect value={billboardId} onChange={setBillboardId} />
                </div>
                <div className="space-y-2">
                  <Label>อาการเสีย *</Label>
                  <SymptomSelect value={symptomId} onChange={setSymptomId} />
                </div>
              </div>

              <div className="space-y-2">
                <Label>อาการอื่น ๆ (ถ้าไม่มีในรายการ)</Label>
                <Input
                  value={symptomOther}
                  onChange={(e) => setSymptomOther(e.target.value)}
                  placeholder="ระบุอาการเสียที่ไม่มีในรายการ"
                />
              </div>

              <div className="space-y-2">
                <Label>รายละเอียดเพิ่มเติม</Label>
                <Textarea
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="อธิบายปัญหาเพิ่มเติม..."
                  rows={3}
                />
              </div>

              <div className="grid md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label>ชื่อช่างแจ้ง</Label>
                  <Input value={technicianName} onChange={(e) => setTechnicianName(e.target.value)} placeholder="ชื่อ-สกุล" />
                </div>
                <div className="space-y-2">
                  <Label>เบอร์ติดต่อ</Label>
                  <Input value={technicianPhone} onChange={(e) => setTechnicianPhone(e.target.value)} placeholder="08x-xxx-xxxx" />
                </div>
                <div className="space-y-2">
                  <Label>ระดับความสำคัญ</Label>
                  <select
                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                  >
                    <option value="low">ต่ำ</option>
                    <option value="normal">ปกติ</option>
                    <option value="high">สูง</option>
                    <option value="urgent">ด่วนมาก</option>
                  </select>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2">
                <Button variant="outline" onClick={resetForm}>ล้างฟอร์ม</Button>
                <Button onClick={handleSubmit} disabled={submitting}>
                  {submitting ? "กำลังบันทึก..." : "สร้างคำขอ Swap"}
                </Button>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      <SwapWizardDialog
        open={wizardOpen}
        onOpenChange={setWizardOpen}
        request={selectedRequest}
        onCompleted={() => {
          setWizardOpen(false);
          setSelectedRequest(null);
          fetchRequests();
        }}
      />
    </div>
  );
}
